export default [
  'PostsBrowse', 
  'PostsRead', 
  'PostsEdit', 
  'PostsAdd', 
  'CategoryBrowse',
  'CategoryRead',
  'CategoryEdit',
  'CategoryAdd',
  'TagsBrowse',
  'TagsRead',
  'TagsEdit',
  'TagsAdd',
  'CommentBrowse',
  'CommentRead',
  'CommentEdit',
]